version: "3.9"
services:
  dev:
    tty: true
    stdin_open: true
    image: authns/dev:2.0
    build:
      dockerfile: Dockerfile.now
    volumes: 
      - ${HOME}:/root/hostdir
    container_name: authns_dev_container

