version: "3.9"
services:
  dev:
    tty: true
    stdin_open: true
    image: authns/dev:2.0
    build: .
    volumes: 
      - ${HOME}:/root/hostdir
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: authns_dev_container

